version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && uwsgi --ini uwsgi.ini"
    container_name: django_test
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
